apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app1
    spec:
      containers:
        - name: app1
          image: app1-image:latest
          ports:
            - containerPort: 8282
          envFrom:
            - configMapRef:
                name: app-config

