apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx1
    spec:
      containers:
        - name: nginx1
          image: nginx:latest
          ports:
            - containerPort: 8282
          volumeMounts:
            - name: nginx-data
              mountPath: /data
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-pvc

